package com.ulegalize.lawfirm.international;

import java.util.ListResourceBundle;

public class Message_de extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"PAGE", "Buchseite"},
                {"KM", "Km"},
                {"FORFAIT", "Pauschale"},

                {"DROIT_FAMILLE", "Familienrecht (Ehe, Scheidung, Abstammung, Adoption)"},
                {"DROIT_PATRIMONIAL", "Familienvermögensrecht (eheliche Güterstände, Schenkungen, Erbschaft)"},
                {"DROIT_JEUNESSE", "Schutz von Minderjährigen - Jugendrecht"},
                {"DROIT_ENFANT", "Recht des Kindes"},
                {"PROTECTION_PERSONNE", "Schutz der Person und des Eigentums von psychisch Kranken"},
                {"ADMINISTRATION_PROVISOIRE", "Vorläufige Verwaltung"},
                {"PROTECTION_VIE_PRIVEE", "Schutz der Privatsphäre"},
                {"DROITS_REELS_IMMOBILIERS", "Eigentum, Miteigentum, Dienstbarkeiten und andere dingliche Rechte an Immobilien"},
                {"PRIVILEGES_HYPOTHEQUES", "Pfandrechte und Hypotheken"},
                {"EXPROPRIATION", "Enteignung"},
                {"BAUX_LOYER_BAUX_COMMERCIAUX", "Miet- und Gewerbemietverträge"},
                {"DROIT_RURAL", "Pachtverträge und ländliches Recht"},
                {"RESPONSABILITE", "Verantwortung"},
                {"ASSURANCES", "Versicherungen"},
                {"REPARATION_DOMMAGE", "Wiedergutmachung des Schadens"},
                {"DROIT_SAISIES", "Pfändungsrecht"},
                {"ARBITRAGE_NATIONAL_INTERNATIONAL", "Nationale und internationale Schiedsgerichtsbarkeit"},
                {"REGLEMENT_COLLECTIF_DETTES", "Kollektive Schuldenregelung (einschließlich Schuldenmediation)"},
                {"DROIT_SOCIETES", "Gesellschaftsrecht"},
                {"FAILLITES", "Unternehmen in Schwierigkeiten, Liquidationen, Konkurse und Vergleiche"},
                {"ASBL", "Asbl", "VoG"},
                {"CONTRATS_COMMERCIAUX", "Handelsverträge und kommerzieller Vertrieb (Agentur, Verkaufskonzession)"},
                {"DROIT_CONCURRENCE", "Wettbewerbsrecht, Handelspraktiken, Verbraucherrecht, Haftung"},
                {"DROIT_BANCAIRE_CREDIT", "Bank- und Kreditrecht"},
                {"TRANSPORTS_TERRESTRES", "Landverkehr"},
                {"TRANSPORTS_FLUVIAUX", "Flussverkehr"},
                {"TRANSPORTS_AERIENS", "Luftverkehr"},
                {"DROIT_MARITIME", "Seerecht"},
                {"DROITS_AUTEUR", "Urheberrecht, literarisches und künstlerisches Eigentum"},
                {"BREVETS", "Patente, Marken, Modelle"},
                {"DROIT_TRAVAIL", "Arbeitsrecht"},
                {"DROIT_SECU_SOCIALE", "Recht der sozialen Sicherheit"},
                {"IMPOTS_DIRECTS", "Direkte Steuern (von natürlichen Personen, Unternehmen und juristischen Personen)"},
                {"IMPOTS_INDIRECTS", "Indirekte Steuern (Mehrwertsteuer, Registrierungssteuer, Erbschaftssteuer, Zoll)"},
                {"DROIT_PENAL_GENERAL", "Allgemeines Strafrecht"},
                {"DROIT_PENAL_AFFAIRES", "Wirtschaftsstrafrecht"},
                {"DROIT_CONSTITUTIONNEL", "Verfassungsrecht"},
                {"ADMINISTRATIF", "Administrativ"},
                {"DROIT_URBANISME_ENVIRONNEMENT", "Stadtplanungs- und Umweltrecht"},
                {"DROIT_MARCHES_PUBLICS", "Stadtplanungs- und Umweltrecht"},
                {"DROIT_AGENTS_ETAT", "Recht der Staatsbediensteten, der halbstaatlichen Einrichtungen und des Bildungswesens"},
                {"DROIT_ETRANGERS", "Ausländerrecht"},
                {"DROIT_INTERNATIONAL_PRIVE", "Internationales Privatrecht"},
                {"DROIT_INTERNATIONAL_PUBLIC", "Internationales öffentliches Recht"},
                {"DROIT_CONCURENCE", "Wettbewerbsrecht"},
                {"LIBRE_CIRCULATION_MARCHANDISES", "Freier Warenverkehr und andere Freiheiten"},
                {"FONCTION_PUBLIQUE_EUROPEENNE", "Europäischer öffentlicher Dienst"},
                {"DROIT_INFORMATIQUE", "Computerrecht"},
                {"DROIT_COMMUNICATIONS_ELECTRONIQUES", "Recht der elektronischen Kommunikation"},
                {"MEDIATION_FAMILIALE", "Familienmediation"},
                {"MEDIATION_MATIERE_SOCIALE", "Mediation in sozialen Angelegenheiten"},
                {"MEDIATION_CIVILE_COMMERCIALE", "Mediation in Zivil- und Handelssachen"},
                {"MEDIATION_PENALE", "Mediation in Strafsachen (siehe Strafrecht)"},
                {"MEDIATION_DETTES", "Schuldenmediation (siehe Gerichtsrecht)"},
                {"DROIT_RESPONSABILITE_MEDICALE", "Arzthaftungsrecht"},
                {"DROIT_HOSPITALIER", "Krankenhausrecht"},
                {"DROIT_PHARMACEUTIQUE", "Pharmazeutisches Recht"},

                {"DROIT_FAMILLE_ET_PERSONNES", "Droit de la famille et des personnes"},
                {"DROIT_BIENS", "Droit des biens"},
                {"ASSURANCES", "Responsabilité civile, assurances, circulation routière"},
                {"DROIT_CONSTRUCTION", "Droit de la construction"},
                {"DROIT_JUDICIAIRE", "Droit judiciaire"},
                {"SOCIETES", "Sociétés"},
                {"DROIT_COMMERCIAL", "Droit commercial"},
                {"DROIT_TRANSPORTS", "Droit des transports (terrestres, fluviaux et aériens) et droits maritimes"},
                {"DROITS_INTELLECTUELS", "Droits intellectuels (droits d auteurs, brevets, marques, modèles)"},
                {"DROIT_SOCIAL", "Droit social"},
                {"DROIT_FISCAL", "Droit fiscal"},
                {"DROIT_PENAL", "Droit pénal"},
                {"DROIT_PUBLIC", "Droit public"},
                {"DROIT_HUMANITAIRE", "Droit humanitaire"},
                {"DROIT_INTERNATIONAL", "Droit international"},
                {"DROIT_EUROPEEN", "Droit européen"},
                {"DROIT_TECHNOLOGIES", "Droit des technologies de l'information et de la communication"},
                {"MEDIATION", "Médiation"},
                {"DROIT_MEDICAL", "Droit médical"},
                {"DROIT_MEDIAS", "Droit des médias"},
                {"DROIT_SPORT", "Droit du sport"},
                {"SPECIFIER", "A spécifier"},

                {"DROIT_FAMILLE_ET_PERSONNES", "Familienrecht und Personenrecht"},
                {"DROIT_BIENS", "Vermögensrecht"},
                {"ASSURANCES", "Haftpflicht, Versicherungen, Straßenverkehr"},
                {"DROIT_CONSTRUCTION", "Baurecht"},
                {"DROIT_JUDICIAIRE", "Richterliches Recht"},
                {"SOCIETES", "Gesellschaften"},
                {"DROIT_COMMERCIAL", "Handelsrecht"},
                {"DROIT_TRANSPORTS", "Transportrecht (Land-, Fluss- und Luftverkehr) und Seerecht"},
                {"DROITS_INTELLECTUELS", "Geistige Rechte (Urheberrechte, Patente, Marken, Modelle)"},
                {"DROIT_SOCIAL", "Sozialrecht"},
                {"DROIT_FISCAL", "Steuerrecht"},
                {"DROIT_PENAL", "Strafrecht"},
                {"DROIT_PUBLIC", "Öffentliches Recht"},
                {"DROIT_HUMANITAIRE", "Humanitäres Recht"},
                {"DROIT_INTERNATIONAL", "Internationales Recht"},
                {"DROIT_EUROPEEN", "Europäisches Recht"},
                {"DROIT_TECHNOLOGIES", "Recht der Informations- und Kommunikationstechnologie"},
                {"MEDIATION", "Vermittlung"},
                {"DROIT_MEDICAL", "Medizinisches Recht"},
                {"DROIT_MEDIAS", "Medienrecht"},
                {"DROIT_SPORT", "Sportrecht"},
                {"SPECIFIER", "Zu spezifizieren"},

                {"PENDING", "Warten"},
                {"REFUSED", "Sich weigern"},
                {"ACCEPTED", "Akzeptiert"},
        };
    }

}
