package com.ulegalize.lawfirm.international;

import java.util.ListResourceBundle;

public class Message_en extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"PAGE", "Page"},
                {"KM", "Km"},
                {"FORFAIT", "Flat rate"},

                {"DROIT_FAMILLE", "Family law (marriage, divorce, filiation, adoption)"},
                {"DROIT_PATRIMONIAL", "Family law (matrimonial property regimes, gifts, inheritance)"},
                {"DROIT_JEUNESSE", "Protection of minors - youth law"},
                {"DROIT_ENFANT", "Children's rights"},
                {"PROTECTION_PERSONNE", "Protection of the person and property of the mentally ill"},
                {"ADMINISTRATION_PROVISOIRE", "Provisional administration"},
                {"PROTECTION_VIE_PRIVEE", "Privacy protection"},
                {"DROITS_REELS_IMMOBILIERS", "Ownership, co-ownership, easements and other real property rights"},
                {"PRIVILEGES_HYPOTHEQUES", "Privileges and mortgages"},
                {"EXPROPRIATION", "Expropriation"},
                {"BAUX_LOYER_BAUX_COMMERCIAUX", "Leases and commercial leases"},
                {"DROIT_RURAL", "Farm leases and rural law"},
                {"RESPONSABILITE", "Responsibility"},
                {"ASSURANCES", "Insurance"},
                {"REPARATION_DOMMAGE", "Compensation for damage"},
                {"DROIT_SAISIES", "Seizure law"},
                {"ARBITRAGE_NATIONAL_INTERNATIONAL", "National and international arbitration"},
                {"REGLEMENT_COLLECTIF_DETTES", "Collective debt settlement (including debt mediation)"},
                {"DROIT_SOCIETES", "Company law"},
                {"FAILLITES", "Companies in difficulty, liquidations, bankruptcies and compositions"},
                {"ASBL", "Asbl", "non-profit association"},
                {"CONTRATS_COMMERCIAUX", "Commercial contracts and commercial distribution (agency, sales concession)"},
                {"DROIT_CONCURRENCE", "Competition law, trade practices, consumer law, liability"},
                {"DROIT_BANCAIRE_CREDIT", "Banking and Credit Law"},
                {"TRANSPORTS_TERRESTRES", "Land transport"},
                {"TRANSPORTS_FLUVIAUX", "Inland waterway transport"},
                {"TRANSPORTS_AERIENS", "Air transport"},
                {"DROIT_MARITIME", "Maritime law"},
                {"DROITS_AUTEUR", "Copyright, literary and artistic property"},
                {"BREVETS", "Patents, trademarks, designs"},
                {"DROIT_TRAVAIL", "Labour law"},
                {"DROIT_SECU_SOCIALE", "Social security law"},
                {"IMPOTS_DIRECTS", "Direct taxes (of individuals, companies and legal entities)"},
                {"IMPOTS_INDIRECTS", "Indirect taxes (VAT, registration duty, inheritance tax, customs)"},
                {"DROIT_PENAL_GENERAL", "General criminal law"},
                {"DROIT_PENAL_AFFAIRES", "Business criminal law"},
                {"DROIT_CONSTITUTIONNEL", "Constitutional law"},
                {"ADMINISTRATIF", "Administrative"},
                {"DROIT_URBANISME_ENVIRONNEMENT", "Urban planning and environmental law"},
                {"DROIT_MARCHES_PUBLICS", "Public procurement law"},
                {"DROIT_AGENTS_ETAT", "Law for state, parastatal and educational employees"},
                {"DROIT_ETRANGERS", "Foreigners' law"},
                {"DROIT_INTERNATIONAL_PRIVE", "Private international law"},
                {"DROIT_INTERNATIONAL_PUBLIC", "Public international law"},
                {"DROIT_CONCURENCE", "Competition law"},
                {"LIBRE_CIRCULATION_MARCHANDISES", "Free movement of goods and other freedoms"},
                {"FONCTION_PUBLIQUE_EUROPEENNE", "European public service"},
                {"DROIT_INFORMATIQUE", "Computer lawe"},
                {"DROIT_COMMUNICATIONS_ELECTRONIQUES", "Electronic communications law"},
                {"MEDIATION_FAMILIALE", "Family mediation"},
                {"MEDIATION_MATIERE_SOCIALE", "Mediation in social matters"},
                {"MEDIATION_CIVILE_COMMERCIALE", "Civil and commercial mediation"},
                {"MEDIATION_PENALE", "Criminal mediation (see criminal law)"},
                {"MEDIATION_DETTES", "Debt mediation (see judicial law)"},
                {"DROIT_RESPONSABILITE_MEDICALE", "Medical liability law"},
                {"DROIT_HOSPITALIER", "Hospital law"},
                {"DROIT_PHARMACEUTIQUE", "Pharmaceutical law"},

                {"DROIT_FAMILLE_ET_PERSONNES", "Family and personal law"},
                {"DROIT_BIENS", "Property law"},
                {"ASSURANCES", "Civil liability, insurance, road traffic"},
                {"DROIT_CONSTRUCTION", "Construction law"},
                {"DROIT_JUDICIAIRE", "Judiciary law"},
                {"SOCIETES", "Companies"},
                {"DROIT_COMMERCIAL", "Commercial law"},
                {"DROIT_TRANSPORTS", "Transport law (land, water and air) and maritime law"},
                {"DROITS_INTELLECTUELS", "Intellectual rights (copyright, patents, trademarks, designs)"},
                {"DROIT_SOCIAL", "Social law"},
                {"DROIT_FISCAL", "Tax law"},
                {"DROIT_PENAL", "Criminal law"},
                {"DROIT_PUBLIC", "Public law"},
                {"DROIT_HUMANITAIRE", "Humanitarian law"},
                {"DROIT_INTERNATIONAL", "International law"},
                {"DROIT_EUROPEEN", "European law"},
                {"DROIT_TECHNOLOGIES", "Information and communication technology law"},
                {"MEDIATION", "Mediation"},
                {"DROIT_MEDICAL", "Medical law"},
                {"DROIT_MEDIAS", "Media law"},
                {"DROIT_SPORT", "Sports law"},
                {"SPECIFIER", "To be specified"},

                {"PENDING", "Pending"},
                {"REFUSED", "Refused"},
                {"ACCEPTED", "Accepted"},
        };
    }

}
