package com.ulegalize.lawfirm.international;

import java.util.ListResourceBundle;

public class Message_nl extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"PAGE", "Bladzijde"},
                {"KM", "Km"},
                {"FORFAIT", "Vast bedrag"},

                {"DROIT_FAMILLE", "Familierecht (huwelijk, echtscheiding, afstamming, adoptie)"},
                {"DROIT_PATRIMONIAL", "Familierecht (huwelijk, echtscheiding, afstamming, adoptie)"},
                {"DROIT_JEUNESSE", "Bescherming van minderjarigen - jeugdwet"},
                {"DROIT_ENFANT", "Het recht van het kind"},
                {"PROTECTION_PERSONNE", "Bescherming van de persoon en de goederen van geesteszieken"},
                {"ADMINISTRATION_PROVISOIRE", "Voorlopige administratie"},
                {"PROTECTION_VIE_PRIVEE", "Bescherming van de privacy"},
                {"DROITS_REELS_IMMOBILIERS", "Eigendom, mede-eigendom, erfdienstbaarheden en andere zakelijke rechten"},
                {"PRIVILEGES_HYPOTHEQUES", "Pandrechten en hypotheken"},
                {"EXPROPRIATION", "Onteigening"},
                {"BAUX_LOYER_BAUX_COMMERCIAUX", "Huurcontracten en commerciële leasing"},
                {"DROIT_RURAL", "Landpacht en plattelandsrecht"},
                {"RESPONSABILITE", "Verantwoordelijkheid"},
                {"ASSURANCES", "Verzekering"},
                {"REPARATION_DOMMAGE", "Vergoeding van de schade"},
                {"DROIT_SAISIES", "Inbeslagname wet"},
                {"ARBITRAGE_NATIONAL_INTERNATIONAL", "Nationale en internationale arbitrage"},
                {"REGLEMENT_COLLECTIF_DETTES", "Collectieve schuldenregeling (met inbegrip van schuldbemiddeling)"},
                {"DROIT_SOCIETES", "Vennootschapsrecht"},
                {"FAILLITES", "Vennootschappen in moeilijkheden, liquidaties, faillissementen en gerechtelijk akkoord"},
                {"ASBL", "Asbl", "Vzw"},
                {"CONTRATS_COMMERCIAUX", "Commerciële contracten en commerciële distributie (agentschap, verkoopconcessie)"},
                {"DROIT_CONCURRENCE", "Mededingingsrecht, handelspraktijken, consumentenrecht, aansprakelijkheid"},
                {"DROIT_BANCAIRE_CREDIT", "Bank- en kredietrecht"},
                {"TRANSPORTS_TERRESTRES", "Vervoer over land"},
                {"TRANSPORTS_FLUVIAUX", "Vervoer over de binnenwateren"},
                {"TRANSPORTS_AERIENS", "Luchtvervoer"},
                {"DROIT_MARITIME", "Maritiem recht"},
                {"DROITS_AUTEUR", "Auteursrecht, literaire en artistieke eigendom"},
                {"BREVETS", "Octrooien, handelsmerken, ontwerpen"},
                {"DROIT_TRAVAIL", "Arbeidsrecht"},
                {"DROIT_SECU_SOCIALE", "Socialezekerheidswetgeving"},
                {"IMPOTS_DIRECTS", "Directe belastingen (van natuurlijke personen, vennootschappen en rechtspersonen)"},
                {"IMPOTS_INDIRECTS", "Indirecte belastingen (BTW, registratierechten, successierechten, douane)"},
                {"DROIT_PENAL_GENERAL", "Algemeen strafrecht"},
                {"DROIT_PENAL_AFFAIRES", "Zakelijk strafrecht"},
                {"DROIT_CONSTITUTIONNEL", "Grondwettelijk recht"},
                {"ADMINISTRATIF", "Administratief"},
                {"DROIT_URBANISME_ENVIRONNEMENT", "Stedenbouw en milieurecht"},
                {"DROIT_MARCHES_PUBLICS", "Wet inzake overheidsopdrachten"},
                {"DROIT_AGENTS_ETAT", "Wet voor staats-, parastatale en onderwijspersoneel"},
                {"DROIT_ETRANGERS", "Vreemdelingenrecht"},
                {"DROIT_INTERNATIONAL_PRIVE", "Internationaal privaatrecht"},
                {"DROIT_INTERNATIONAL_PUBLIC", "Internationaal publiekrecht"},
                {"DROIT_CONCURENCE", "Mededingingsrecht"},
                {"LIBRE_CIRCULATION_MARCHANDISES", "Vrij verkeer van goederen en andere vrijheden"},
                {"FONCTION_PUBLIQUE_EUROPEENNE", "Europees openbaar ambt"},
                {"DROIT_INFORMATIQUE", "Computerrecht"},
                {"DROIT_COMMUNICATIONS_ELECTRONIQUES", "Elektronische communicatiewetgeving"},
                {"MEDIATION_FAMILIALE", "Gezinsbemiddeling"},
                {"MEDIATION_MATIERE_SOCIALE", "Bemiddeling in sociale zaken"},
                {"MEDIATION_CIVILE_COMMERCIALE", "Civiele en commerciële bemiddeling"},
                {"MEDIATION_PENALE", "Strafbemiddeling (zie strafrecht)"},
                {"MEDIATION_DETTES", "Schuldbemiddeling (zie gerechtelijk recht)"},
                {"DROIT_RESPONSABILITE_MEDICALE", "Wet medische aansprakelijkheid"},
                {"DROIT_HOSPITALIER", "Ziekenhuisrecht"},
                {"DROIT_PHARMACEUTIQUE", "Farmaceutisch recht"},

                {"DROIT_FAMILLE_ET_PERSONNES", "Familierecht en personenrecht"},
                {"DROIT_BIENS", "Eigendomsrecht"},
                {"ASSURANCES", "Wettelijke aansprakelijkheid, verzekering, wegverkeer"},
                {"DROIT_CONSTRUCTION", "Bouwrecht"},
                {"DROIT_JUDICIAIRE", "Gerechtelijk recht"},
                {"SOCIETES", "Bedrijven"},
                {"DROIT_COMMERCIAL", "Handelsrecht"},
                {"DROIT_TRANSPORTS", "Vervoersrecht (land, water en lucht) en zeerecht"},
                {"DROITS_INTELLECTUELS", "Intellectuele rechten (auteursrechten, octrooien, merken, modellen)"},
                {"DROIT_SOCIAL", "Sociaal recht"},
                {"DROIT_FISCAL", "Fiscaal recht"},
                {"DROIT_PENAL", "Strafrecht"},
                {"DROIT_PUBLIC", "Publiek recht"},
                {"DROIT_HUMANITAIRE", "Humanitarian law"},
                {"DROIT_INTERNATIONAL", "Internationaal recht"},
                {"DROIT_EUROPEEN", "Europees recht"},
                {"DROIT_TECHNOLOGIES", "Recht inzake informatie- en communicatietechnologie"},
                {"MEDIATION", "Bemiddeling"},
                {"DROIT_MEDICAL", "Medisch recht"},
                {"DROIT_MEDIAS", "Mediawet"},
                {"DROIT_SPORT", "Sportrecht"},
                {"SPECIFIER", "Te specificeren"},

                {"PENDING", "Aan het wachten"},
                {"REFUSED", "Weigeren"},
                {"ACCEPTED", "Geaccepteerd"},
        };
    }

}
