package com.ulegalize.lawfirm.international;

import java.util.ListResourceBundle;

public class Message_fr extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"PAGE", "Page"},
                {"KM", "Km"},
                {"FORFAIT", "Forfait"},

                {"DROIT_FAMILLE", "Droit de la famille(mariage, divorce, filiation, adoption)"},
                {"DROIT_PATRIMONIAL", "Droit patrimonial de la famille(régimes matrimoniaux, donation, succession)"},
                {"DROIT_JEUNESSE", "Protection des mineurs - droit de le jeunesse"},
                {"DROIT_ENFANT", "Droit de l'enfant"},
                {"PROTECTION_PERSONNE", "Protection de la personne et des biens des malades mentaux"},
                {"ADMINISTRATION_PROVISOIRE", "Administration provisoire"},
                {"PROTECTION_VIE_PRIVEE", "Protection de la vie privée"},
                {"DROITS_REELS_IMMOBILIERS", "Propriété, copropriété, servitudes et autres droits réels immobiliers"},
                {"PRIVILEGES_HYPOTHEQUES", "Privilèges et hypothèques"},
                {"EXPROPRIATION", "Expropriation"},
                {"BAUX_LOYER_BAUX_COMMERCIAUX", "Baux à loyer et baux commerciaux"},
                {"DROIT_RURAL", "Baux à ferme et droit rural"},
                {"RESPONSABILITE", "Responsabilité"},
                {"ASSURANCES", "Assurances"},
                {"REPARATION_DOMMAGE", "Réparation du dommage"},
                {"DROIT_SAISIES", "Droit des saisies"},
                {"ARBITRAGE_NATIONAL_INTERNATIONAL", "Arbitrage national et international"},
                {"REGLEMENT_COLLECTIF_DETTES", "Réglement collectif de dettes (y compris médiation de dettes)"},
                {"DROIT_SOCIETES", "Droit des sociétés"},
                {"FAILLITES", "Entreprises en difficulté, liquidations, faillites et concordats"},
                {"ASBL", "Asbl", "non-profit association"},
                {"CONTRATS_COMMERCIAUX", "Contrats commerciaux et distribution commerciale (agence, concession de vente)"},
                {"DROIT_CONCURRENCE", "Droit de la concurrence, pratiques du commerce, droit de la consom., respon"},
                {"DROIT_BANCAIRE_CREDIT", "Droit bancaire et du crédit"},
                {"TRANSPORTS_TERRESTRES", "Transports terrestres"},
                {"TRANSPORTS_FLUVIAUX", "Transports fluviaux"},
                {"TRANSPORTS_AERIENS", "Transports aériens"},
                {"DROIT_MARITIME", "Droit maritime"},
                {"DROITS_AUTEUR", "Droits d'auteur, propriété littéraire et artistique"},
                {"BREVETS", "Brevets, marques, modèles"},
                {"DROIT_TRAVAIL", "Droit du travail"},
                {"DROIT_SECU_SOCIALE", "Droit de la sécurité sociale"},
                {"IMPOTS_DIRECTS", "Impôts directs (des personnes physiques, des sociétés et des personnes morales)"},
                {"IMPOTS_INDIRECTS", "Impôts indirects (T.V.A., droit d'enregistrement, droit de succession, douanes)"},
                {"DROIT_PENAL_GENERAL", "Droit pénal général"},
                {"DROIT_PENAL_AFFAIRES", "Droit pénal des affaires"},
                {"DROIT_CONSTITUTIONNEL", "Droit constitutionnel"},
                {"ADMINISTRATIF", "Administratif"},
                {"DROIT_URBANISME_ENVIRONNEMENT", "Droit de l'urbanisme et de l'environnement"},
                {"DROIT_MARCHES_PUBLICS", "Droit des marchés publics"},
                {"DROIT_AGENTS_ETAT", "Droit des agents de l'Etat, des parastataux et de l'enseignement"},
                {"DROIT_ETRANGERS", "Droit des étrangers"},
                {"DROIT_INTERNATIONAL_PRIVE", "Droit international privé"},
                {"DROIT_INTERNATIONAL_PUBLIC", "Droit international public"},
                {"DROIT_CONCURENCE", "Droit de la concurrence"},
                {"LIBRE_CIRCULATION_MARCHANDISES", "Libre circulation des marchandises et autres libertés"},
                {"FONCTION_PUBLIQUE_EUROPEENNE", "Fonction publique européenne"},
                {"DROIT_INFORMATIQUE", "Droit de l'informatique"},
                {"DROIT_COMMUNICATIONS_ELECTRONIQUES", "Droit des communications électroniques"},
                {"MEDIATION_FAMILIALE", "Médiation familiale"},
                {"MEDIATION_MATIERE_SOCIALE", "Médiation en matière sociale"},
                {"MEDIATION_CIVILE_COMMERCIALE", "Médiation civile et commerciale"},
                {"MEDIATION_PENALE", "Médiation pénale (voir droit pénal)"},
                {"MEDIATION_DETTES", "Médiation de dettes (voir droit judiciaire)"},
                {"DROIT_RESPONSABILITE_MEDICALE", "Droit de la responsabilité médicale"},
                {"DROIT_HOSPITALIER", "Droit hospitalier"},
                {"DROIT_PHARMACEUTIQUE", "Droit pharmaceutique"},

                {"DROIT_FAMILLE_ET_PERSONNES", "Droit de la famille et des personnes"},
                {"DROIT_BIENS", "Droit des biens"},
                {"ASSURANCES", "Responsabilité civile, assurances, circulation routière"},
                {"DROIT_CONSTRUCTION", "Droit de la construction"},
                {"DROIT_JUDICIAIRE", "Droit judiciaire"},
                {"SOCIETES", "Sociétés"},
                {"DROIT_COMMERCIAL", "Droit commercial"},
                {"DROIT_TRANSPORTS", "Droit des transports (terrestres, fluviaux et aériens) et droits maritimes"},
                {"DROITS_INTELLECTUELS", "Droits intellectuels (droits d auteurs, brevets, marques, modèles)"},
                {"DROIT_SOCIAL", "Droit social"},
                {"DROIT_FISCAL", "Droit fiscal"},
                {"DROIT_PENAL", "Droit pénal"},
                {"DROIT_PUBLIC", "Droit public"},
                {"DROIT_HUMANITAIRE", "Droit humanitaire"},
                {"DROIT_INTERNATIONAL", "Droit international"},
                {"DROIT_EUROPEEN", "Droit européen"},
                {"DROIT_TECHNOLOGIES", "Droit des technologies de l'information et de la communication"},
                {"MEDIATION", "Médiation"},
                {"DROIT_MEDICAL", "Droit médical"},
                {"DROIT_MEDIAS", "Droit des médias"},
                {"DROIT_SPORT", "Droit du sport"},
                {"SPECIFIER", "A spécifier"},

                {"PENDING", "En attente"},
                {"REFUSED", "Refusé"},
                {"ACCEPTED", "Accepté"},
        };
    }

}
