
package services.dpa.common.deposit.v01.ws;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "CourtNotFoundFault", targetNamespace = "http://common.dpa.services/addressbook/external/consult/court/v01/messages")
public class CourtNotFoundFault
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private final services.dpa.common.addressbook.external.consult.court.v01.messages.CourtNotFoundFault faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public CourtNotFoundFault(String message, services.dpa.common.addressbook.external.consult.court.v01.messages.CourtNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CourtNotFoundFault(String message, services.dpa.common.addressbook.external.consult.court.v01.messages.CourtNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: services.dpa.common.addressbook.external.consult.court.v01.messages.CourtNotFoundFault
     */
    public services.dpa.common.addressbook.external.consult.court.v01.messages.CourtNotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
