
package services.dpa.common.deposit.v01.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import services.dpa.common.deposit.consult.v01.messages.*;
import services.dpa.common.deposit.file.v01.messages.FileDeleteRequest;
import services.dpa.common.deposit.file.v01.messages.FileDeleteResponse;
import services.dpa.common.deposit.file.v01.messages.FileUploadRequest;
import services.dpa.common.deposit.file.v01.messages.FileUploadResponse;
import services.dpa.common.deposit.price.v01.messages.PriceRequest;
import services.dpa.common.deposit.price.v01.messages.PriceResponse;
import services.dpa.common.deposit.v01.messages.DepositRequest;
import services.dpa.common.deposit.v01.messages.DepositResponse;
import services.dpa.common.deposit.v01.messages.GetDocTypesRequest;
import services.dpa.common.deposit.v01.messages.GetDocTypesResponse;
import services.dpa.common.global.v01.messages.Ping;
import services.dpa.common.global.v01.messages.Pong;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "DepositPort", targetNamespace = "http://common.dpa.services/deposit/v01/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        services.dpa.common.deposit.v01.types.ObjectFactory.class,
        services.dpa.common.addressbook.base.v01.types.ObjectFactory.class,
        services.dpa.common.addressbook.external.consult.court.v01.messages.ObjectFactory.class,
        services.dpa.common.addressbook.external.consult.court.v01.types.ObjectFactory.class,
        services.dpa.common.addressbook.external.consult.lawyer.v01.messages.ObjectFactory.class,
        services.dpa.common.addressbook.external.consult.lawyer.v01.types.ObjectFactory.class,
        services.dpa.common.addressbook.external.v01.types.ObjectFactory.class,
        services.dpa.common.deposit.base.v01.types.ObjectFactory.class,
        services.dpa.common.deposit.consult.v01.messages.ObjectFactory.class,
        services.dpa.common.deposit.consult.v01.types.ObjectFactory.class,
        services.dpa.common.deposit.file.v01.messages.ObjectFactory.class,
        services.dpa.common.deposit.file.v01.types.ObjectFactory.class,
        services.dpa.common.deposit.price.v01.messages.ObjectFactory.class,
        services.dpa.common.deposit.price.v01.types.ObjectFactory.class,
        services.dpa.common.deposit.v01.messages.ObjectFactory.class,
        services.dpa.common.global.v01.messages.ObjectFactory.class,
        services.dpa.common.global.v01.types.ObjectFactory.class,
        services.dpa.common.global.v01.codes.ObjectFactory.class,
        services.dpa.common.addressbook.base.v01.codes.ObjectFactory.class
})
public interface DepositPort {


    /**
     * @param part1
     * @return returns services.dpa.common.deposit.v01.messages.DepositResponse
     * @throws Deposit1Fault
     */
    @WebMethod(action = "deposit")
    @WebResult(name = "DepositResponse", targetNamespace = "http://common.dpa.services/deposit/v01/messages", partName = "part1")
    DepositResponse deposit(
            @WebParam(name = "DepositRequest", targetNamespace = "http://common.dpa.services/deposit/v01/messages", partName = "part1")
            DepositRequest part1)
            throws Deposit1Fault
    ;

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.file.v01.messages.FileUploadResponse
     * @throws FileUpload1Fault
     */
    @WebMethod(action = "fileUpload")
    @WebResult(name = "FileUploadResponse", targetNamespace = "http://common.dpa.services/deposit/file/v01/messages", partName = "part1")
    FileUploadResponse fileUpload(
            @WebParam(name = "FileUploadRequest", targetNamespace = "http://common.dpa.services/deposit/file/v01/messages", partName = "part1")
            FileUploadRequest part1)
            throws FileUpload1Fault
    ;

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.file.v01.messages.FileDeleteResponse
     * @throws FileDelete1Fault
     */
    @WebMethod(action = "fileDelete")
    @WebResult(name = "FileDeleteResponse", targetNamespace = "http://common.dpa.services/deposit/file/v01/messages", partName = "part1")
    FileDeleteResponse fileDelete(
            @WebParam(name = "FileDeleteRequest", targetNamespace = "http://common.dpa.services/deposit/file/v01/messages", partName = "part1")
            FileDeleteRequest part1)
            throws FileDelete1Fault
    ;

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.v01.messages.GetDocTypesResponse
     */
    @WebMethod(action = "getDocTypes")
    @WebResult(name = "getDocTypesResponse", targetNamespace = "http://common.dpa.services/deposit/v01/messages", partName = "part1")
    GetDocTypesResponse getDocTypes(
            @WebParam(name = "getDocTypesRequest", targetNamespace = "http://common.dpa.services/deposit/v01/messages", partName = "part1")
            GetDocTypesRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.price.v01.messages.PriceResponse
     * @throws Price1Fault
     */
    @WebMethod(action = "calculatePrice")
    @WebResult(name = "PriceResponse", targetNamespace = "http://common.dpa.services/deposit/price/v01/messages", partName = "part1")
    PriceResponse calculatePrice(
            @WebParam(name = "PriceRequest", targetNamespace = "http://common.dpa.services/deposit/price/v01/messages", partName = "part1")
            PriceRequest part1)
            throws Price1Fault
    ;

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.consult.v01.messages.GetLawyerChannelInfoResponse
     * @throws LawyerNotFoundFault
     */
    @WebMethod(action = "getLawyerChannelInfo")
    @WebResult(name = "getLawyerChannelInfoResponse", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
    GetLawyerChannelInfoResponse getLawyerChannelInfo(
            @WebParam(name = "getLawyerChannelInfoRequest", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
            GetLawyerChannelInfoRequest part1)
            throws LawyerNotFoundFault
    ;

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.consult.v01.messages.GetCourtChannelInfoResponse
     * @throws CourtNotFoundFault
     * @throws LanguageNotFoundFault
     */
    @WebMethod(action = "getCourtChannelInfo")
    @WebResult(name = "getCourtChannelInfoResponse", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
    GetCourtChannelInfoResponse getCourtChannelInfo(
            @WebParam(name = "getCourtChannelInfoRequest", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
            GetCourtChannelInfoRequest part1)
            throws CourtNotFoundFault, LanguageNotFoundFault
    ;

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.consult.v01.messages.GetThirdPartyChannelInfoResponse
     */
    @WebMethod(action = "getThirdPartyChannelInfo")
    @WebResult(name = "getThirdPartyChannelInfoResponse", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
    GetThirdPartyChannelInfoResponse getThirdPartyChannelInfo(
            @WebParam(name = "getThirdPartyChannelInfoRequest", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
            GetThirdPartyChannelInfoRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.deposit.consult.v01.messages.IsUserAllowedToDepositResponse
     */
    @WebMethod(action = "isUserAllowedToDeposit")
    @WebResult(name = "isUserAllowedToDepositResponse", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
    IsUserAllowedToDepositResponse isUserAllowedToDeposit(
            @WebParam(name = "isUserAllowedToDepositRequest", targetNamespace = "http://common.dpa.services/deposit/consult/v01/messages", partName = "part1")
            IsUserAllowedToDepositRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.global.v01.messages.Pong
     * @throws PingFault
     */
    @WebMethod(action = "ping")
    @WebResult(name = "Pong", targetNamespace = "http://common.dpa.services/global/v01/messages", partName = "part1")
    Pong ping(
            @WebParam(name = "Ping", targetNamespace = "http://common.dpa.services/global/v01/messages", partName = "part1")
            Ping part1)
            throws PingFault
    ;

}
