
package services.dpa.common.deposit.v01.ws;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "DepositService", targetNamespace = "http://common.dpa.services/deposit/v01/ws", wsdlLocation = "https://cs.acc.dp-a.be/api/ws/depositService?wsdl")
public class DepositService
        extends Service {

    private final static URL DEPOSITSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEPOSITSERVICE_EXCEPTION;
    private final static QName DEPOSITSERVICE_QNAME = new QName("http://common.dpa.services/deposit/v01/ws", "DepositService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cs.acc.dp-a.be/api/ws/depositService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPOSITSERVICE_WSDL_LOCATION = url;
        DEPOSITSERVICE_EXCEPTION = e;
    }

    public DepositService() {
        super(__getWsdlLocation(), DEPOSITSERVICE_QNAME);
    }

    public DepositService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPOSITSERVICE_QNAME, features);
    }

    public DepositService(URL wsdlLocation) {
        super(wsdlLocation, DEPOSITSERVICE_QNAME);
    }

    public DepositService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPOSITSERVICE_QNAME, features);
    }

    public DepositService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepositService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPOSITSERVICE_EXCEPTION != null) {
            throw DEPOSITSERVICE_EXCEPTION;
        }
        return DEPOSITSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns DepositPort
     */
    @WebEndpoint(name = "DepositPortTypeBindingPort")
    public DepositPort getDepositPortTypeBindingPort() {
        return super.getPort(new QName("http://common.dpa.services/deposit/v01/ws", "DepositPortTypeBindingPort"), DepositPort.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DepositPort
     */
    @WebEndpoint(name = "DepositPortTypeBindingPort")
    public DepositPort getDepositPortTypeBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.dpa.services/deposit/v01/ws", "DepositPortTypeBindingPort"), DepositPort.class, features);
    }

}
