
package services.dpa.common.deposit.v01.ws;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "FileUpload1Fault", targetNamespace = "http://common.dpa.services/deposit/file/v01/messages")
public class FileUpload1Fault
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private final services.dpa.common.deposit.file.v01.messages.FileUpload1Fault faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public FileUpload1Fault(String message, services.dpa.common.deposit.file.v01.messages.FileUpload1Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FileUpload1Fault(String message, services.dpa.common.deposit.file.v01.messages.FileUpload1Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: services.dpa.common.deposit.file.v01.messages.FileUpload1Fault
     */
    public services.dpa.common.deposit.file.v01.messages.FileUpload1Fault getFaultInfo() {
        return faultInfo;
    }

}
