
package services.dpa.common.deposit.v01.ws;

import jakarta.xml.ws.WebFault;
import services.dpa.common.global.v01.messages.GeneralFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "GeneralFault", targetNamespace = "http://common.dpa.services/global/v01/messages")
public class PingFault
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private final GeneralFault faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public PingFault(String message, GeneralFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PingFault(String message, GeneralFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: services.dpa.common.global.v01.messages.GeneralFault
     */
    public GeneralFault getFaultInfo() {
        return faultInfo;
    }

}
