
package services.dpa.common.message.box.v01.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import services.dpa.common.global.v01.messages.Ping;
import services.dpa.common.global.v01.messages.Pong;
import services.dpa.common.message.box.v01.messages.*;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "BoxPort", targetNamespace = "http://common.dpa.services/message/box/v01/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        services.dpa.common.message.box.v01.messages.ObjectFactory.class,
        services.dpa.common.message.box.v01.types.ObjectFactory.class,
        services.dpa.common.addressbook.base.v01.types.ObjectFactory.class,
        services.dpa.common.global.v01.messages.ObjectFactory.class,
        services.dpa.common.global.v01.types.ObjectFactory.class,
        services.dpa.common.global.v01.codes.ObjectFactory.class,
        services.dpa.common.addressbook.base.v01.codes.ObjectFactory.class,
        services.dpa.common.message.base.v01.codes.ObjectFactory.class
})
public interface BoxPort {


    /**
     * @param part1
     * @return returns services.dpa.common.message.box.v01.messages.GetBoxesResponse
     */
    @WebMethod(action = "getBoxes")
    @WebResult(name = "getBoxesResponse", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
    GetBoxesResponse getBoxes(
            @WebParam(name = "getBoxesRequest", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
            GetBoxesRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.message.box.v01.messages.GetMessageSummariesResponse
     */
    @WebMethod(action = "getMessageSummaries")
    @WebResult(name = "getMessageSummariesResponse", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
    GetMessageSummariesResponse getMessageSummaries(
            @WebParam(name = "getMessageSummariesRequest", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
            GetMessageSummariesRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.message.box.v01.messages.GetMessageByIdResponse
     */
    @WebMethod(action = "getMessageById")
    @WebResult(name = "getMessageByIdResponse", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
    GetMessageByIdResponse getMessageById(
            @WebParam(name = "getMessageByIdRequest", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
            GetMessageByIdRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.message.box.v01.messages.GetDocumentResponse
     */
    @WebMethod(action = "getDocument")
    @WebResult(name = "getDocumentResponse", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
    GetDocumentResponse getDocument(
            @WebParam(name = "getDocumentRequest", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
            GetDocumentRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.message.box.v01.messages.GetCasesResponse
     */
    @WebMethod(action = "getCases")
    @WebResult(name = "getCasesResponse", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
    GetCasesResponse getCases(
            @WebParam(name = "getCasesRequest", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
            GetCasesRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.message.box.v01.messages.GetCaseDocumentsResponse
     */
    @WebMethod(action = "getCaseDocuments")
    @WebResult(name = "getCaseDocumentsResponse", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
    GetCaseDocumentsResponse getCaseDocuments(
            @WebParam(name = "getCaseDocumentsRequest", targetNamespace = "http://common.dpa.services/message/box/v01/messages", partName = "part1")
            GetCaseDocumentsRequest part1);

    /**
     * @param part1
     * @return returns services.dpa.common.global.v01.messages.Pong
     * @throws PingFault
     */
    @WebMethod(action = "ping")
    @WebResult(name = "Pong", targetNamespace = "http://common.dpa.services/global/v01/messages", partName = "part1")
    Pong ping(
            @WebParam(name = "Ping", targetNamespace = "http://common.dpa.services/global/v01/messages", partName = "part1")
            Ping part1)
            throws PingFault
    ;

}
