
package services.dpa.common.message.box.v01.ws;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "BoxService", targetNamespace = "http://common.dpa.services/message/box/v01/ws", wsdlLocation = "https://cs.acc.dp-a.be/api/ws/boxService?wsdl")
public class BoxService
        extends Service {

    private final static URL BOXSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOXSERVICE_EXCEPTION;
    private final static QName BOXSERVICE_QNAME = new QName("http://common.dpa.services/message/box/v01/ws", "BoxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cs.acc.dp-a.be/api/ws/boxService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOXSERVICE_WSDL_LOCATION = url;
        BOXSERVICE_EXCEPTION = e;
    }

    public BoxService() {
        super(__getWsdlLocation(), BOXSERVICE_QNAME);
    }

    public BoxService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOXSERVICE_QNAME, features);
    }

    public BoxService(URL wsdlLocation) {
        super(wsdlLocation, BOXSERVICE_QNAME);
    }

    public BoxService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOXSERVICE_QNAME, features);
    }

    public BoxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoxService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (BOXSERVICE_EXCEPTION != null) {
            throw BOXSERVICE_EXCEPTION;
        }
        return BOXSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns BoxPort
     */
    @WebEndpoint(name = "BoxPortTypeBindingPort")
    public BoxPort getBoxPortTypeBindingPort() {
        return super.getPort(new QName("http://common.dpa.services/message/box/v01/ws", "BoxPortTypeBindingPort"), BoxPort.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BoxPort
     */
    @WebEndpoint(name = "BoxPortTypeBindingPort")
    public BoxPort getBoxPortTypeBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.dpa.services/message/box/v01/ws", "BoxPortTypeBindingPort"), BoxPort.class, features);
    }

}
